-- Create a table to track site statistics
create table if not exists public.site_stats (
  id bigint generated by default as identity primary key,
  total_views bigint default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert the initial record if it doesn't exist
insert into public.site_stats (id, total_views)
values (1, 0)
on conflict (id) do nothing;

-- Enable RLS
alter table public.site_stats enable row level security;

-- Policy: Everyone can read stats
create policy "Stats are public"
  on public.site_stats for select
  using ( true );

-- Policy: No one can update directly (must use RPC)
create policy "No direct updates"
  on public.site_stats for update
  using ( false );

-- Function to safely increment view count
create or replace function public.increment_site_views()
returns bigint
language plpgsql
security definer
as $$
declare
  new_count bigint;
begin
  update public.site_stats
  set total_views = total_views + 1,
      updated_at = now()
  where id = 1
  returning total_views into new_count;
  
  return new_count;
end;
$$;
