-- Create a table for public profile information
create table public.profile (
  id bigint generated by default as identity primary key,
  cv_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert initial row
insert into public.profile (id, cv_url)
values (1, null);

-- Enable Row Level Security (RLS)
alter table public.profile enable row level security;

-- Create policies
create policy "Public profiles are viewable by everyone."
  on public.profile for select
  using ( true );

create policy "Users can update their own profile."
  on public.profile for update
  using ( auth.role() = 'authenticated' );

-- Storage Bucket for Documents
insert into storage.buckets (id, name, public) 
values ('documents', 'documents', true);

-- Storage Policies
create policy "CVs are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'documents' );

create policy "Authenticated users can upload CVs."
  on storage.objects for insert
  with check ( bucket_id = 'documents' and auth.role() = 'authenticated' );

create policy "Authenticated users can update CVs."
  on storage.objects for update
  with check ( bucket_id = 'documents' and auth.role() = 'authenticated' );
